WEB_APP = r'''<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#020503"><title>Rachel IA</title>
<style>
:root{color-scheme:dark;--g:#19f67d;--gold:#ffd659;--text:#effff6;--muted:#789184}*{box-sizing:border-box}html,body{height:100%}body{margin:0;overflow:hidden;background:#020503;color:var(--text);font:15px Inter,system-ui,sans-serif}body:before{content:"";position:fixed;inset:0;pointer-events:none;background:radial-gradient(circle at 50% 31%,rgba(20,246,119,.1),transparent 34%),radial-gradient(circle at 50% 110%,rgba(9,73,39,.16),transparent 42%)}
#particles{position:fixed;inset:0;width:100%;height:100%;pointer-events:none;opacity:.86}.shell{position:relative;z-index:1;height:100dvh;min-height:540px;display:grid;grid-template-rows:auto 1fr auto;padding:24px clamp(16px,3vw,44px) 20px}.topbar{display:flex;align-items:center;justify-content:space-between;letter-spacing:.15em;text-transform:uppercase;font-size:11px;color:var(--muted)}.brand,.status{display:flex;align-items:center;gap:10px}.dot{width:6px;height:6px;border-radius:50%;background:var(--g);box-shadow:0 0 14px var(--g)}.status .dot{animation:status 2.8s ease-in-out infinite}
.workspace{min-height:0;width:min(940px,100%);margin:0 auto;display:grid;grid-template-rows:minmax(290px,58vh) 1fr}.heart-zone{position:relative;display:grid;place-items:center;min-height:0}.heart{position:relative;width:clamp(285px,42vmin,505px);aspect-ratio:1;animation:float 7s ease-in-out infinite;isolation:isolate}.heart:before{content:"";position:absolute;inset:15%;border-radius:50%;background:rgba(20,255,123,.1);filter:blur(38px);animation:aura 4.6s ease-in-out infinite;z-index:-1}#coreCanvas{display:block;width:100%;height:100%;filter:drop-shadow(0 0 19px rgba(24,255,121,.22))}.heart.thinking{animation-duration:3.6s}.heart.thinking:after{content:"ANALISANDO";position:absolute;left:50%;bottom:2%;translate:-50%;font-size:9px;letter-spacing:.32em;color:rgba(111,255,176,.7)}
#messages{min-height:0;overflow:auto;display:flex;flex-direction:column;gap:12px;padding:0 clamp(4px,4vw,44px) 16px;scrollbar-width:thin;scrollbar-color:#19422c transparent;mask-image:linear-gradient(transparent,#000 18px)}.welcome{margin:auto auto 8px;text-align:center;color:var(--muted)}.welcome strong{display:block;margin-bottom:7px;color:#e6fff0;font-size:clamp(20px,2.4vw,29px);font-weight:500}.welcome span{font-size:13px}.message{max-width:min(76%,680px);padding:10px 14px;line-height:1.6;white-space:pre-wrap;overflow-wrap:anywhere;border-radius:15px;animation:message .28s ease-out both}.assistant{align-self:flex-start;background:linear-gradient(90deg,rgba(13,37,23,.54),rgba(8,20,13,.12));border-left:1px solid rgba(50,255,140,.48)}.user{align-self:flex-end;background:linear-gradient(270deg,rgba(22,63,39,.72),rgba(9,27,17,.32));border-right:1px solid rgba(70,255,150,.5)}
.composer-wrap{width:min(790px,100%);margin:auto}.composer{display:grid;grid-template-columns:1fr 43px;align-items:end;gap:8px;padding:7px 7px 7px 15px;background:rgba(3,9,6,.84);border:1px solid rgba(70,255,149,.19);border-radius:23px;box-shadow:0 13px 50px rgba(0,0,0,.46);backdrop-filter:blur(15px)}.composer:focus-within{border-color:rgba(52,255,137,.48)}textarea{width:100%;min-height:43px;max-height:120px;resize:none;padding:11px 3px 9px;background:transparent;border:0;outline:0;color:var(--text);font:inherit}textarea::placeholder{color:#587063}button{width:43px;height:43px;display:grid;place-items:center;padding:0;border:0;border-radius:50%;background:linear-gradient(145deg,#27f987,#0bb45a);color:#011f0d;cursor:pointer;box-shadow:0 0 19px rgba(26,247,122,.2);transition:.18s}button:hover{transform:translateY(-1px) scale(1.03);filter:brightness(1.09)}button:disabled{opacity:.42;cursor:wait}button svg{width:18px;fill:currentColor}.hint{text-align:center;margin:8px 0 0;color:#43584c;font-size:10px}
@keyframes float{0%,100%{transform:translateY(5px) scale(.99)}50%{transform:translateY(-11px) scale(1.012)}}@keyframes spin{to{transform:rotate(360deg)}}@keyframes reverse{to{transform:rotate(-360deg)}}@keyframes pulse{0%,100%{transform:scale(.78);opacity:.72;box-shadow:0 0 12px 3px rgba(46,255,139,.18)}50%{transform:scale(1.18);opacity:1;box-shadow:0 0 30px 9px rgba(46,255,139,.33)}}@keyframes aura{50%{transform:scale(1.1)}}@keyframes status{50%{opacity:.38;transform:scale(.78)}}@keyframes message{from{opacity:0;transform:translateY(7px)}}
@media(max-height:760px){.workspace{grid-template-rows:minmax(240px,49vh) 1fr}.heart{width:clamp(245px,38vmin,390px)}}@media(max-width:620px){.shell{padding:17px 13px 13px}.workspace{grid-template-rows:minmax(280px,53vh) 1fr}.heart{width:min(86vw,420px)}.message{max-width:88%}.hint{display:none}}@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation-duration:.001ms!important;animation-iteration-count:1!important}#particles{display:none}}
</style></head><body>
<canvas id="particles" aria-hidden="true"></canvas><main class="shell"><header class="topbar"><div class="brand"><span class="dot"></span><span>Rachel IA</span></div><div class="status"><span class="dot"></span><span id="statusText">Núcleo online</span></div></header><section class="workspace"><div class="heart-zone" aria-label="Núcleo visual animado da Rachel IA"><div class="heart" id="heart"><canvas id="coreCanvas" aria-label="Núcleo de energia animado"></canvas></div></div><div id="messages" aria-live="polite"><div class="welcome" id="welcome"><strong>Olá, eu sou a Rachel.</strong><span>O núcleo está online. Como posso ajudar?</span></div></div></section><div class="composer-wrap"><form class="composer" id="form"><textarea id="input" rows="1" maxlength="12000" placeholder="Converse com a Rachel..." aria-label="Mensagem para Rachel" required></textarea><button id="send" type="submit" aria-label="Enviar mensagem"><svg viewBox="0 0 24 24"><path d="M21.7 2.3a1 1 0 0 0-1-.24l-18 7a1 1 0 0 0 .08 1.89l7.34 2.45 2.45 7.34a1 1 0 0 0 1.88.08l7.5-17.5a1 1 0 0 0-.25-1.02ZM13.68 17.7l-1.7-5.1L16 8.58l-5.1 3.4-4.83-1.61 12.95-5.04-5.34 12.37Z"/></svg></button></form><p class="hint">Enter para enviar · Shift + Enter para nova linha</p></div></main>
<script>
const messages=document.querySelector('#messages'),form=document.querySelector('#form'),input=document.querySelector('#input'),send=document.querySelector('#send'),heart=document.querySelector('#heart'),statusText=document.querySelector('#statusText');let conversationId=null;function add(text,role){document.querySelector('#welcome')?.remove();const item=document.createElement('div');item.className='message '+role;item.textContent=text;messages.appendChild(item);messages.scrollTo({top:messages.scrollHeight,behavior:'smooth'})}function busy(on){send.disabled=on;heart.classList.toggle('thinking',on);statusText.textContent=on?'Rachel está pensando':'Núcleo online'}function resize(){input.style.height='auto';input.style.height=Math.min(input.scrollHeight,120)+'px'}form.addEventListener('submit',async e=>{e.preventDefault();const content=input.value.trim();if(!content||send.disabled)return;add(content,'user');input.value='';resize();busy(true);try{const response=await fetch('/v1/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content,conversation_id:conversationId})});const data=await response.json();if(!response.ok)throw new Error(data.message||data.error||'Falha no núcleo.');conversationId=data.conversation_id;add(data.message.content,'assistant')}catch(error){add('Não consegui concluir essa resposta: '+error.message,'assistant')}finally{busy(false);input.focus()}});input.addEventListener('input',resize);input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}});input.focus();
const coreCanvas=document.querySelector('#coreCanvas'),coreCtx=coreCanvas.getContext('2d');let coreSize=0,coreDpr=1,energy=[];const ringAxes=[[.08,.08,0],[1.18,.05,.35],[-1.05,.18,-.55],[.46,1.02,.72],[-.52,.9,-.82]];
function resizeCore(){const box=coreCanvas.getBoundingClientRect();coreDpr=Math.min(devicePixelRatio||1,2);coreSize=Math.max(280,Math.round(box.width));coreCanvas.width=coreSize*coreDpr;coreCanvas.height=coreSize*coreDpr;coreCtx.setTransform(coreDpr,0,0,coreDpr,0,0);energy=Array.from({length:105},()=>({ring:Math.floor(Math.random()*ringAxes.length),a:Math.random()*6.283,s:.002+Math.random()*.006,size:.35+Math.random()*1.5,gold:Math.random()<.09,life:Math.random()*6.283}))}
function rotatePoint(x,y,z,rx,ry,rz){let c=Math.cos(rx),s=Math.sin(rx),y1=y*c-z*s,z1=y*s+z*c;c=Math.cos(ry);s=Math.sin(ry);let x1=x*c+z1*s,z2=-x*s+z1*c;c=Math.cos(rz);s=Math.sin(rz);return{x:x1*c-y1*s,y:x1*s+y1*c,z:z2}}
function pointOnRing(a,axis,time,index){const wobble=1+Math.sin(a*5+time*.0012+index)*.018;return rotatePoint(Math.cos(a)*wobble,Math.sin(a)*wobble,0,axis[0]+Math.sin(time*.00012+index)*.16,axis[1]+time*(.000045+(index%2)*.000017),axis[2]+Math.cos(time*.0001+index)*.12)}
function pathRing(axis,time,index,radius,alpha){coreCtx.beginPath();for(let i=0;i<=180;i++){const a=i/180*6.283,p=pointOnRing(a,axis,time,index),perspective=1/(1.22-p.z*.14),x=coreSize/2+p.x*radius*perspective,y=coreSize/2+p.y*radius*perspective;(i?coreCtx.lineTo(x,y):coreCtx.moveTo(x,y))}coreCtx.strokeStyle=`rgba(24,255,119,${alpha})`;coreCtx.lineWidth=index===0?1.25:.72;coreCtx.shadowColor='#16ff72';coreCtx.shadowBlur=index===0?14:8;coreCtx.stroke();coreCtx.shadowBlur=0}
function drawCore(time){coreCtx.clearRect(0,0,coreSize,coreSize);const active=heart.classList.contains('thinking'),speed=active?2.7:1,pulse=1+Math.sin(time*(active ? .008 : .0025))*(active ? .055 : .025),radius=coreSize*.34*pulse;
 const haze=coreCtx.createRadialGradient(coreSize/2,coreSize/2,0,coreSize/2,coreSize/2,radius*1.25);haze.addColorStop(0,'rgba(35,255,126,.07)');haze.addColorStop(.62,'rgba(10,165,72,.025)');haze.addColorStop(1,'rgba(0,0,0,0)');coreCtx.fillStyle=haze;coreCtx.fillRect(0,0,coreSize,coreSize);
 ringAxes.forEach((axis,i)=>pathRing(axis,time*speed,i,radius*(i?1:.96),i?(.23+(i%2)*.08):.5));
 for(const d of energy){d.a+=d.s*speed;d.life+=.035;const p=pointOnRing(d.a,ringAxes[d.ring],time*speed,d.ring),perspective=1/(1.22-p.z*.14),x=coreSize/2+p.x*radius*perspective,y=coreSize/2+p.y*radius*perspective,alpha=(.35+.55*(p.z+1)/2)*(.55+.45*Math.sin(d.life));coreCtx.beginPath();coreCtx.fillStyle=d.gold?`rgba(255,214,82,${alpha})`:`rgba(84,255,157,${alpha})`;coreCtx.shadowColor=d.gold?'#ffd652':'#19ff79';coreCtx.shadowBlur=5+d.size*4;coreCtx.arc(x,y,d.size*(.7+perspective*.35),0,6.283);coreCtx.fill()}
 coreCtx.shadowBlur=0;for(let i=5;i>=1;i--){coreCtx.beginPath();coreCtx.strokeStyle=`rgba(58,255,142,${.055+i*.035})`;coreCtx.lineWidth=.65+i*.28;coreCtx.arc(coreSize/2,coreSize/2,radius*(.12+i*.052)+Math.sin(time*.002+i)*2,0,6.283);coreCtx.stroke()}
 const coreRadius=radius*(active ? .13 : .105)*(1+Math.sin(time*(active ? .009 : .003))*.12),glow=coreCtx.createRadialGradient(coreSize/2,coreSize/2,0,coreSize/2,coreSize/2,coreRadius*2.6);glow.addColorStop(0,'rgba(255,255,255,1)');glow.addColorStop(.12,'rgba(210,255,225,.98)');glow.addColorStop(.38,'rgba(34,255,125,.82)');glow.addColorStop(1,'rgba(18,255,111,0)');coreCtx.fillStyle=glow;coreCtx.beginPath();coreCtx.arc(coreSize/2,coreSize/2,coreRadius*2.6,0,6.283);coreCtx.fill();requestAnimationFrame(drawCore)}
new ResizeObserver(resizeCore).observe(coreCanvas);resizeCore();requestAnimationFrame(drawCore);
const canvas=document.querySelector('#particles'),ctx=canvas.getContext('2d');let dots=[],w=0,h=0,dpr=1;function reset(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);const count=Math.min(150,Math.max(60,Math.round(w*h/11500)));dots=Array.from({length:count},()=>({a:Math.random()*6.283,r:40+Math.random()*Math.min(w,h)*.31,s:(Math.random()*.00055+.00012)*(Math.random()<.5?-1:1),z:Math.random(),size:.45+Math.random()*1.25,gold:Math.random()<.13,tw:Math.random()*6.283}))}function draw(){ctx.clearRect(0,0,w,h);const cx=w/2,cy=Math.min(h*.39,340);for(const d of dots){d.a+=d.s;d.tw+=.025;const x=cx+Math.cos(d.a)*d.r,y=cy+Math.sin(d.a)*d.r*(.55+.24*d.z),alpha=(.17+.55*d.z)*(.64+.36*Math.sin(d.tw));ctx.beginPath();ctx.fillStyle=d.gold?`rgba(255,214,89,${alpha})`:`rgba(31,255,129,${alpha})`;ctx.shadowColor=d.gold?'#ffd659':'#19f67d';ctx.shadowBlur=5+d.z*9;ctx.arc(x,y,d.size*(.7+d.z),0,6.283);ctx.fill()}ctx.shadowBlur=0;requestAnimationFrame(draw)}addEventListener('resize',reset,{passive:true});if(!matchMedia('(prefers-reduced-motion: reduce)').matches){reset();requestAnimationFrame(draw)}
</script></body></html>'''
